output "ecr_repository_url" {
  description = "Full URL of the ECR repository"
  value       = module.backend.ecr_repository_url
}

output "ecr_repository_name" {
  description = "Name of the ECR repository"
  value       = module.backend.ecr_repository_name
}

output "frontend_bucket" {
  description = "Name of the frontend S3 bucket"
  value       = module.frontend.frontend_bucket
}

output "cloudfront_distribution_id" {
  description = "ID of the CloudFront distribution"
  value       = module.frontend.cloudfront_distribution_id
}

output "cloudfront_domain_name" {
  description = "Domain name of the CloudFront distribution"
  value       = module.frontend.cloudfront_domain_name
}

output "api_asg_name" {
  description = "Name of the API Auto Scaling Group"
  value       = module.backend.asg_name
}

output "ssm_prefix" {
  description = "SSM Parameter Store prefix"
  value       = local.ssm_prefix
}

output "github_actions_role_arn" {
  description = "ARN of the GitHub Actions IAM Role"
  value       = module.github_oidc.github_actions_role_arn
}

output "route53_nameservers" {
  description = "Nameservers generated by AWS Route 53 (Copy these into Namecheap -> Custom DNS)"
  value       = module.frontend.route53_nameservers
}

output "acm_validation_records" {
  description = "CNAME records for ACM DNS validation (if using Namecheap Advanced DNS instead of Route 53)"
  value       = module.frontend.acm_validation_records
}
